language: csharp
solution: f_stop.sln

mono:
- 4.6.1

cache:
  directories:
  - packages

before_script:
- if [ "$TRAVIS_TAG" ]; then export TAG_VERSION="$TRAVIS_TAG.$TRAVIS_BUILD_NUMBER"; else export TAG_VERSION="v1.0.0.$TRAVIS_BUILD_NUMBER"; fi
- export TAG_VERSION=`echo $TAG_VERSION | sed 's/v//'`
- echo "Setting version to '$TAG_VERSION'"
- sed -i "s/1\.0\.\*/$TAG_VERSION/" Source/LibWhipLru/Properties/AssemblyInfo.cs
- sed -i "s/1\.0\.\*/$TAG_VERSION/" Source/f_stop/Properties/AssemblyInfo.cs
- sed -i 's/COMPILED_BY = "?mono?"/COMPILED_BY = "Mono"/' Source/f_stop/Program.cs
- sed -i 's/COMPILED_BY = "?mono?"/COMPILED_BY = "Mono"/' Source/RollbarCrashReporter/CrashReporter.cs

before_deploy:
- >-
  if [ "$TRAVIS_TAG" ]; then
    export ENVIRONMENT=production
    sed -i 's/param name="Environment" value="development"/param name="Environment" value="production"/' bin/f_stop.exe.config;
    sed -i 's/param name="Environment" value="development"/param name="Environment" value="production"/' bin/RollbarCrashReporter.exe.config;
  else
    export ENVIRONMENT=test
    sed -i 's/param name="Environment" value="development"/param name="Environment" value="test"/' bin/f_stop.exe.config;
    sed -i 's/param name="Environment" value="development"/param name="Environment" value="test"/' bin/RollbarCrashReporter.exe.config;
  fi
- mv bin f-stop
- zip -r f-stop-mono.zip f-stop > /dev/null

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ""
  file: f-stop-mono.zip
  draft: true
  on:
    repo: kf6kjg/f-stop
    tags: true

after_deploy:
- export LOCAL_USERNAME="`git log -n 1 --pretty=format:"%an"`"
- export REVISION="`git log -n 1 --pretty=format:"%H"`"
- curl https://api.rollbar.com/api/1/deploy/ -F access_token="$ACCESS_TOKEN" -F environment="$ENVIRONMENT" -F revision="$REVISION" -F local_username="$LOCAL_USERNAME"

